"""init schema

Revision ID: 04cee76d7b4d
Revises: ccce1f86d42e
Create Date: 2025-08-15 13:21:31.563422-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04cee76d7b4d'
down_revision = 'ccce1f86d42e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
