"""init schema

Revision ID: 0727eca25963
Revises: 3b6796b8f0f5
Create Date: 2025-08-16 15:22:37.709220-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0727eca25963'
down_revision = '3b6796b8f0f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
