"""init schema

Revision ID: 0ced9ecd6281
Revises: 72eeccadc09c
Create Date: 2025-08-16 01:12:05.686597-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ced9ecd6281'
down_revision = '72eeccadc09c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
