"""init schema

Revision ID: 15383d3a1605
Revises: ea9e8b1a4f92
Create Date: 2025-08-17 02:35:49.340410-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15383d3a1605'
down_revision = 'ea9e8b1a4f92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
