"""init schema

Revision ID: 18cdd6cbce6d
Revises: 0ced9ecd6281
Create Date: 2025-08-16 01:17:12.945996-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18cdd6cbce6d'
down_revision = '0ced9ecd6281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
