"""init schema

Revision ID: 22532f892a08
Revises: 2a9e66530ecb
Create Date: 2025-06-08 05:55:16.757349-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22532f892a08'
down_revision = '2a9e66530ecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
