"""init schema

Revision ID: 22cfedc0a844
Revises: 5203ae984582
Create Date: 2025-08-15 15:06:04.905357-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22cfedc0a844'
down_revision = '5203ae984582'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
