"""init schema

Revision ID: 24b4e1a7d8ee
Revises: 36d1848dec3f
Create Date: 2025-06-11 13:44:17.837583-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24b4e1a7d8ee'
down_revision = '36d1848dec3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
