"""init schema

Revision ID: 2564191dd338
Revises: b6f0e7f4d72c
Create Date: 2025-06-08 02:08:21.331911-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2564191dd338'
down_revision = 'b6f0e7f4d72c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
