"""init schema

Revision ID: 296b85fdd76b
Revises: 3299ea6f9356
Create Date: 2025-08-17 03:16:45.774455-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '296b85fdd76b'
down_revision = '3299ea6f9356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
