"""init schema

Revision ID: 2c3971997baf
Revises: c8cbcd23ee3c
Create Date: 2025-08-17 03:41:28.698121-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c3971997baf'
down_revision = 'c8cbcd23ee3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
