"""init schema

Revision ID: 2c495f1d318c
Revises: e5153fb9649c
Create Date: 2025-08-15 02:47:40.997825-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c495f1d318c'
down_revision = 'e5153fb9649c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
