"""init schema

Revision ID: 3299ea6f9356
Revises: 552f87148a6e
Create Date: 2025-08-17 03:15:53.078690-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3299ea6f9356'
down_revision = '552f87148a6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
