"""init schema

Revision ID: 32aa091cc808
Revises: eb74c00b5666
Create Date: 2025-08-16 02:31:39.853631-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32aa091cc808'
down_revision = 'eb74c00b5666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
