"""init schema

Revision ID: 338661200c1b
Revises: 09cfcdaca510
Create Date: 2025-07-14 13:40:12.878128-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338661200c1b'
down_revision = '09cfcdaca510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
