"""init schema

Revision ID: 35802ee76f30
Revises: 91ab2d74b1c2
Create Date: 2025-08-17 02:39:54.788080-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35802ee76f30'
down_revision = '91ab2d74b1c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
