"""init schema

Revision ID: 36a3d41d2dfb
Revises: d351252c471d
Create Date: 2025-08-17 03:49:09.511003-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36a3d41d2dfb'
down_revision = 'd351252c471d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
