"""init schema

Revision ID: 38399001e704
Revises: c8c77000a4ce
Create Date: 2025-08-17 03:18:28.093763-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38399001e704'
down_revision = 'c8c77000a4ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
