"""init schema

Revision ID: 39fed50c9c82
Revises: 5b71c901b75f
Create Date: 2025-07-13 07:40:17.380146-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39fed50c9c82'
down_revision = '5b71c901b75f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
