"""init schema

Revision ID: 3ba88f3bae05
Revises: ce21784245e2
Create Date: 2025-08-17 02:50:32.287744-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ba88f3bae05'
down_revision = 'ce21784245e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
