"""init schema

Revision ID: 3dd352fc847a
Revises: ea01235ee450
Create Date: 2025-07-14 05:17:01.477670-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dd352fc847a'
down_revision = 'ea01235ee450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
