"""init schema

Revision ID: 4905eafb70f8
Revises: 97f21e3a51fa
Create Date: 2025-08-17 04:18:35.500378-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4905eafb70f8'
down_revision = '97f21e3a51fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
