"""init schema

Revision ID: 4cd324269114
Revises: 2f7bdba63326
Create Date: 2025-07-13 05:07:22.831204-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cd324269114'
down_revision = '2f7bdba63326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
