"""init schema

Revision ID: 4cd6b84e5660
Revises: 9a1a1b8d5827
Create Date: 2025-08-15 09:56:37.069474-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cd6b84e5660'
down_revision = '9a1a1b8d5827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
