"""init schema

Revision ID: 4d70e0e1342c
Revises: 0727eca25963
Create Date: 2025-08-17 02:31:05.860526-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d70e0e1342c'
down_revision = '0727eca25963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
