"""init schema

Revision ID: 5086920271d7
Revises: 8e9eefbe166e
Create Date: 2025-06-08 02:35:48.443712-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5086920271d7'
down_revision = '8e9eefbe166e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
