"""init schema

Revision ID: 5230bf652b17
Revises: a2f4b3933d4b
Create Date: 2025-07-13 06:11:56.347492-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5230bf652b17'
down_revision = 'a2f4b3933d4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
