"""init schema

Revision ID: 5388164b85d5
Revises: 5953958ab5ac
Create Date: 2025-08-17 03:30:18.066198-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5388164b85d5'
down_revision = '5953958ab5ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
