"""init schema

Revision ID: 552f87148a6e
Revises: b9d7d37278fb
Create Date: 2025-08-17 03:08:02.316608-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '552f87148a6e'
down_revision = 'b9d7d37278fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
