"""init schema

Revision ID: 5953958ab5ac
Revises: 38399001e704
Create Date: 2025-08-17 03:22:21.849233-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5953958ab5ac'
down_revision = '38399001e704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
