"""init schema

Revision ID: 5cee10a368f8
Revises: de3230bfaf7e
Create Date: 2025-06-22 07:13:22.295477-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cee10a368f8'
down_revision = 'de3230bfaf7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
