"""init schema

Revision ID: 65b5820caa67
Revises: 02ea4ed60233
Create Date: 2025-08-16 12:32:44.515448-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65b5820caa67'
down_revision = '02ea4ed60233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building_prerequisite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_level_id', sa.Integer(), nullable=False),
    sa.Column('required_building_type_id', sa.Integer(), nullable=False),
    sa.Column('required_level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_level_id'], ['building_level.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['required_building_type_id'], ['building_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_level_id', 'required_building_type_id', name='uq_building_level_requirement')
    )
    op.add_column('building_level', sa.Column('population_required', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('building_level', 'population_required')
    op.drop_table('building_prerequisite')
    # ### end Alembic commands ###
