"""init schema

Revision ID: 6859107e100c
Revises: 631631bd5f6c
Create Date: 2025-08-15 11:51:47.242848-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6859107e100c'
down_revision = '631631bd5f6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
