"""init schema

Revision ID: 6f768506598b
Revises: bb8471fc989d
Create Date: 2025-08-15 13:54:29.320834-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f768506598b'
down_revision = 'bb8471fc989d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
