"""init schema

Revision ID: 7c964b110fb7
Revises: bdfcccd355c0
Create Date: 2025-06-08 05:13:29.547677-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c964b110fb7'
down_revision = 'bdfcccd355c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_tile_resource_layout',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('map_tile_id', sa.Integer(), nullable=False),
    sa.Column('resource_type_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['map_tile_id'], ['map_tile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_type_id'], ['resources_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('map_tile_id', 'resource_type_id', name='uq_tile_resource')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map_tile_resource_layout')
    # ### end Alembic commands ###
