"""init schema

Revision ID: 850c36941e54
Revises: 3dd352fc847a
Create Date: 2025-07-14 05:19:09.229186-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '850c36941e54'
down_revision = '3dd352fc847a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
