"""init schema

Revision ID: 8a988076070c
Revises: d99cee32e12e
Create Date: 2025-06-08 01:43:10.238474-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a988076070c'
down_revision = 'd99cee32e12e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
