"""init schema

Revision ID: 8df35eef0d35
Revises: 39fed50c9c82
Create Date: 2025-07-13 07:43:39.301504-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8df35eef0d35'
down_revision = '39fed50c9c82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
