"""init schema

Revision ID: 912326151a47
Revises: 73105bd4e175
Create Date: 2025-06-11 13:35:36.526355-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '912326151a47'
down_revision = '73105bd4e175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
