"""init schema

Revision ID: 9323e9684093
Revises: 3de60a2a71fb
Create Date: 2025-06-11 13:52:44.851898-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9323e9684093'
down_revision = '3de60a2a71fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
