"""init schema

Revision ID: 97f21e3a51fa
Revises: 36a3d41d2dfb
Create Date: 2025-08-17 04:02:22.853746-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97f21e3a51fa'
down_revision = '36a3d41d2dfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
