"""init schema

Revision ID: a2f4b3933d4b
Revises: f962da69b891
Create Date: 2025-07-13 05:50:30.267237-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2f4b3933d4b'
down_revision = 'f962da69b891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
