"""init schema

Revision ID: a4c72fc9c997
Revises: 5388164b85d5
Create Date: 2025-08-17 03:30:57.699576-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4c72fc9c997'
down_revision = '5388164b85d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
