"""init schema

Revision ID: a9794ba8f5d0
Revises: 2c495f1d318c
Create Date: 2025-08-15 03:40:04.454365-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9794ba8f5d0'
down_revision = '2c495f1d318c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('tribe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tribe_id'], ['tribe_attributes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'tribe_id', name='uq_buildingtype_name_tribe')
    )
    op.create_table('building_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_type_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('construction_time', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_type_id'], ['building_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_type_id', 'level', name='uq_building_type_level')
    )
    op.create_table('building_upgrade_resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_level_id', sa.Integer(), nullable=False),
    sa.Column('resource_type_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_level_id'], ['building_level.id'], ),
    sa.ForeignKeyConstraint(['resource_type_id'], ['resources_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_level_id', 'resource_type_id', name='uq_building_upgrade')
    )
    op.create_index(op.f('ix_building_upgrade_resource_building_level_id'), 'building_upgrade_resource', ['building_level_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_building_upgrade_resource_building_level_id'), table_name='building_upgrade_resource')
    op.drop_table('building_upgrade_resource')
    op.drop_table('building_level')
    op.drop_table('building_type')
    # ### end Alembic commands ###
