"""init schema

Revision ID: ab3243ed36e8
Revises: f84719263ab5
Create Date: 2025-08-16 10:37:40.552780-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab3243ed36e8'
down_revision = 'f84719263ab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
