"""init schema

Revision ID: af964c6bc61a
Revises: 8439dd50991c
Create Date: 2025-07-14 13:24:59.109149-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af964c6bc61a'
down_revision = '8439dd50991c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
