"""init schema

Revision ID: b3315cd6190b
Revises: 72b988da0e12
Create Date: 2025-08-15 12:48:54.000453-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3315cd6190b'
down_revision = '72b988da0e12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
