"""init schema

Revision ID: b474b8240c3f
Revises: d9d5d0649e50
Create Date: 2025-06-08 01:39:31.165053-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b474b8240c3f'
down_revision = 'd9d5d0649e50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
