"""init schema

Revision ID: b6f0e7f4d72c
Revises: 65d933b633e8
Create Date: 2025-06-08 01:51:15.100704-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f0e7f4d72c'
down_revision = '65d933b633e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
