"""init schema

Revision ID: b838fd71980e
Revises: 8a988076070c
Create Date: 2025-06-08 01:43:38.226989-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b838fd71980e'
down_revision = '8a988076070c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
