"""init schema

Revision ID: b9d7d37278fb
Revises: 3ba88f3bae05
Create Date: 2025-08-17 03:07:22.357602-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9d7d37278fb'
down_revision = '3ba88f3bae05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
