"""init schema

Revision ID: bd4f415f0234
Revises: 9323e9684093
Create Date: 2025-06-11 13:55:56.538326-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd4f415f0234'
down_revision = '9323e9684093'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
