"""init schema

Revision ID: c670e6d1968d
Revises: d38e8f757e43
Create Date: 2025-06-22 07:50:16.397788-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c670e6d1968d'
down_revision = 'd38e8f757e43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
