"""init schema

Revision ID: c8c77000a4ce
Revises: 296b85fdd76b
Create Date: 2025-08-17 03:17:34.419084-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8c77000a4ce'
down_revision = '296b85fdd76b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
