"""init schema

Revision ID: c8cbcd23ee3c
Revises: a4c72fc9c997
Create Date: 2025-08-17 03:38:26.737875-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8cbcd23ee3c'
down_revision = 'a4c72fc9c997'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
