"""init schema

Revision ID: ca3845a0d6b8
Revises: b654b5a1638f
Create Date: 2025-06-20 13:27:42.533330-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca3845a0d6b8'
down_revision = 'b654b5a1638f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
