"""init schema

Revision ID: ccce1f86d42e
Revises: b3315cd6190b
Create Date: 2025-08-15 12:58:50.317947-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccce1f86d42e'
down_revision = 'b3315cd6190b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
