"""init schema

Revision ID: cce374dc1a5f
Revises: 4905eafb70f8
Create Date: 2025-08-17 04:35:21.113023-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cce374dc1a5f'
down_revision = '4905eafb70f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
