"""init schema

Revision ID: cda4558db173
Revises: 4d70e0e1342c
Create Date: 2025-08-17 02:32:08.220262-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda4558db173'
down_revision = '4d70e0e1342c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
