"""init schema

Revision ID: ce21784245e2
Revises: 35802ee76f30
Create Date: 2025-08-17 02:49:54.005608-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce21784245e2'
down_revision = '35802ee76f30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
