"""init schema

Revision ID: d351252c471d
Revises: 2c3971997baf
Create Date: 2025-08-17 03:48:25.977281-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd351252c471d'
down_revision = '2c3971997baf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
