"""init schema

Revision ID: d438068a79e3
Revises: ee87e178cea5
Create Date: 2025-08-16 01:30:58.083933-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd438068a79e3'
down_revision = 'ee87e178cea5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
