"""init schema

Revision ID: d50f642788c5
Revises: b6212c678ef2
Create Date: 2025-06-07 11:36:00.191576-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd50f642788c5'
down_revision = 'b6212c678ef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
