"""init schema

Revision ID: d61c34ebb18f
Revises: cce374dc1a5f
Create Date: 2025-08-17 04:36:28.367017-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd61c34ebb18f'
down_revision = 'cce374dc1a5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
