"""init schema

Revision ID: d89862f44e85
Revises: eb8986db2a3d
Create Date: 2025-08-17 13:40:34.426982-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd89862f44e85'
down_revision = 'eb8986db2a3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
