"""init schema

Revision ID: d99cee32e12e
Revises: b474b8240c3f
Create Date: 2025-06-08 01:42:10.006286-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd99cee32e12e'
down_revision = 'b474b8240c3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
