"""init schema

Revision ID: daffea86f933
Revises: d89862f44e85
Create Date: 2025-08-17 13:42:01.989155-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daffea86f933'
down_revision = 'd89862f44e85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
