"""init schema

Revision ID: dd4de7d94386
Revises: 4cd324269114
Create Date: 2025-07-13 05:22:25.114961-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd4de7d94386'
down_revision = '4cd324269114'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
