"""init schema

Revision ID: de3230bfaf7e
Revises: 600646ff51de
Create Date: 2025-06-22 07:00:37.692712-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de3230bfaf7e'
down_revision = '600646ff51de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
