"""init schema

Revision ID: e71ce4374a95
Revises: 2564191dd338
Create Date: 2025-06-08 02:31:06.762849-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e71ce4374a95'
down_revision = '2564191dd338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
