"""init schema

Revision ID: e948bbaaa5c0
Revises: 5230bf652b17
Create Date: 2025-07-13 06:17:22.318703-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e948bbaaa5c0'
down_revision = '5230bf652b17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
