"""init schema

Revision ID: ea01235ee450
Revises: f42905a9be87
Create Date: 2025-07-14 05:11:43.731668-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea01235ee450'
down_revision = 'f42905a9be87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
