"""init schema

Revision ID: ea9e8b1a4f92
Revises: cda4558db173
Create Date: 2025-08-17 02:35:04.551509-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea9e8b1a4f92'
down_revision = 'cda4558db173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
