"""init schema

Revision ID: eb74c00b5666
Revises: 5086f04e7438
Create Date: 2025-08-16 02:30:18.368485-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb74c00b5666'
down_revision = '5086f04e7438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
