"""init schema

Revision ID: eb8986db2a3d
Revises: d61c34ebb18f
Create Date: 2025-08-17 05:38:51.381339-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb8986db2a3d'
down_revision = 'd61c34ebb18f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
