"""init schema

Revision ID: ec4e84b8e8de
Revises: 94b010cbe06d
Create Date: 2025-08-16 02:18:49.976593-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec4e84b8e8de'
down_revision = '94b010cbe06d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
