"""init schema

Revision ID: ee194fe764b8
Revises: 22cfedc0a844
Create Date: 2025-08-16 01:05:42.334900-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee194fe764b8'
down_revision = '22cfedc0a844'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
