"""init schema

Revision ID: ef0d32ba6a0d
Revises: daf8bce0467b
Create Date: 2025-08-15 15:01:18.067237-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef0d32ba6a0d'
down_revision = 'daf8bce0467b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
