"""init schema

Revision ID: f62323437a2f
Revises: 8f561b1a8f95
Create Date: 2025-06-08 01:35:41.433750-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f62323437a2f'
down_revision = '8f561b1a8f95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
