"""init schema

Revision ID: f962da69b891
Revises: fc6e91c2bf0e
Create Date: 2025-07-13 05:42:42.288235-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f962da69b891'
down_revision = 'fc6e91c2bf0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
