"""init schema

Revision ID: fb46636ed3f5
Revises: ce2ad17bb914
Create Date: 2025-08-15 13:46:15.062857-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb46636ed3f5'
down_revision = 'ce2ad17bb914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
