"""init schema

Revision ID: fc6e91c2bf0e
Revises: dd4de7d94386
Create Date: 2025-07-13 05:37:26.238835-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc6e91c2bf0e'
down_revision = 'dd4de7d94386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
