map_tile:
  size: 100
  constructible_ratio: 0.9
  layouts:
    - layout: [[CROP, 15], [WOOD, 1], [CLAY, 1], [IRON, 1]]
      weight: 0.02
    - layout: [[CROP, 9], [WOOD, 3], [CLAY, 3], [IRON, 3]]
      weight: 0.05
    - layout: [[CROP, 6], [WOOD, 4], [CLAY, 4], [IRON, 4]]
      weight: 0.31
    - layout: [[CROP, 5], [WOOD, 5], [CLAY, 4], [IRON, 4]]
      weight: 0.21
    - layout: [[CROP, 5], [WOOD, 4], [CLAY, 5], [IRON, 4]]
      weight: 0.21
    - layout: [[CROP, 5], [WOOD, 4], [CLAY, 4], [IRON, 5]]
      weight: 0.20

capacities:
  granary:
    "0": 400
    "1": 1700
    "2": 3400
    "3": 5100
    "4": 6800
    "5": 8500
    "6": 10200
    "7": 11900
    "8": 13600
    "9": 15300
    "10": 17000
  warehouse:
    "0": 500
    "1": 800
    "2": 1550
    "3": 2350
    "4": 3200
    "5": 4100
    "6": 5050
    "7": 6050
    "8": 7100
    "9": 8200
    "10": 9350

buildings:
  - name: "Main Building"
    description: "Reduces construction time"
    levels:
      - level: 1
        time: 60
        cost: { WOOD: 70, CLAY: 40, IRON: 60, CROP: 20 }
      - level: 2
        time: 80
        cost: { WOOD: 90, CLAY: 50, IRON: 75, CROP: 25 }

  - name: "Warehouse"
    description: "Stores wood, clay, and iron"
    levels:
      - level: 1
        time: 50
        population_required: 20
        cost: { WOOD: 130, CLAY: 160, IRON: 90, CROP: 40 }
      - level: 2
        time: 65
        population_required: 40
        cost: { WOOD: 165, CLAY: 205, IRON: 120, CROP: 55 }

  - name: "Granary"
    description: "Stores crop"
    levels:
      - level: 1
        time: 50
        cost: { WOOD: 80, CLAY: 100, IRON: 70, CROP: 20 }
      - level: 2
        time: 65
        cost: { WOOD: 100, CLAY: 125, IRON: 90, CROP: 30 }

  - name: "Barracks"
    description: "Trains infantry units"
    levels:
      - level: 1
        time: 90
        population_required: 50
        cost: { WOOD: 210, CLAY: 140, IRON: 260, CROP: 120 }
        prerequisites:
          - building: "Main Building"
            level: 2
      - level: 2
        time: 110
        population_required: 80
        cost: { WOOD: 270, CLAY: 180, IRON: 330, CROP: 160 }
        prerequisites:
          - building: "Main Building"
            level: 3
          - building: "Granary"
            level: 2
