"""init schema

Revision ID: 02ea4ed60233
Revises: ab3243ed36e8
Create Date: 2025-08-16 10:39:57.772033-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02ea4ed60233'
down_revision = 'ab3243ed36e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
