"""init schema

Revision ID: 09cfcdaca510
Revises: af964c6bc61a
Create Date: 2025-07-14 13:39:44.529334-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09cfcdaca510'
down_revision = 'af964c6bc61a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
