"""init schema

Revision ID: 1441d16034f1
Revises: a9794ba8f5d0
Create Date: 2025-08-15 09:45:55.988358-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1441d16034f1'
down_revision = 'a9794ba8f5d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
