"""init schema

Revision ID: 1bb8fd7f486c
Revises: 3711dc9203a4
Create Date: 2025-08-15 14:50:09.113686-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bb8fd7f486c'
down_revision = '3711dc9203a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
