"""init schema

Revision ID: 1ff989b9872a
Revises: e71ce4374a95
Create Date: 2025-06-08 02:33:22.384206-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ff989b9872a'
down_revision = 'e71ce4374a95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
