"""Add VillageResourceStorage and FarmUpgrade models

Revision ID: 2660694a469a
Revises: e948bbaaa5c0
Create Date: 2025-07-13 07:24:34.728060-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2660694a469a'
down_revision = 'e948bbaaa5c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('village_resource_storage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.Column('resource_type_id', sa.Integer(), nullable=False),
    sa.Column('stored_amount', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resource_type_id'], ['resources_types.id'], ),
    sa.ForeignKeyConstraint(['village_id'], ['village.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('village_id', 'resource_type_id', name='uq_village_resource')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('village_resource_storage')
    # ### end Alembic commands ###
