"""update village farms transaction table

Revision ID: 270436073b31
Revises: ea5365bf9934
Create Date: 2025-03-02 06:55:48.437522-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '270436073b31'
down_revision = 'ea5365bf9934'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
