"""init schema

Revision ID: 29a9636b112d
Revises: d6bc3afd752d
Create Date: 2025-06-08 01:47:21.059264-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29a9636b112d'
down_revision = 'd6bc3afd752d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
