"""init schema

Revision ID: 2a9e66530ecb
Revises: 7c964b110fb7
Create Date: 2025-06-08 05:28:24.906076-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a9e66530ecb'
down_revision = '7c964b110fb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
