"""init schema

Revision ID: 2b49c84525d9
Revises: 6859107e100c
Create Date: 2025-08-15 11:52:30.689174-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b49c84525d9'
down_revision = '6859107e100c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
