"""init schema

Revision ID: 2f7bdba63326
Revises: 6b0fac79bd74
Create Date: 2025-06-22 08:09:40.142544-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f7bdba63326'
down_revision = '6b0fac79bd74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
