"""init schema

Revision ID: 36d1848dec3f
Revises: 912326151a47
Create Date: 2025-06-11 13:43:42.726512-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36d1848dec3f'
down_revision = '912326151a47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
