"""init schema

Revision ID: 3711dc9203a4
Revises: 6f768506598b
Create Date: 2025-08-15 13:55:08.281459-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3711dc9203a4'
down_revision = '6f768506598b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
