"""init schema

Revision ID: 3b6796b8f0f5
Revises: caf957266c3c
Create Date: 2025-08-16 15:20:45.962370-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b6796b8f0f5'
down_revision = 'caf957266c3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
