"""init schema

Revision ID: 3de60a2a71fb
Revises: 7eef5ee314fd
Create Date: 2025-06-11 13:52:25.448354-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3de60a2a71fb'
down_revision = '7eef5ee314fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
