"""init schema

Revision ID: 40e27e5b57a3
Revises: 9276bda8de99
Create Date: 2025-08-15 09:46:56.719672-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40e27e5b57a3'
down_revision = '9276bda8de99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
