"""init schema

Revision ID: 48d91eb43dd8
Revises: fe3a4ceae315
Create Date: 2025-06-22 07:53:27.786992-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48d91eb43dd8'
down_revision = 'fe3a4ceae315'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
