"""init schema

Revision ID: 4a2ca894ddef
Revises: 40e27e5b57a3
Create Date: 2025-08-15 09:48:04.485813-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a2ca894ddef'
down_revision = '40e27e5b57a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
