"""init schema

Revision ID: 5086f04e7438
Revises: 5b81f7e9caee
Create Date: 2025-08-16 02:28:34.745245-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5086f04e7438'
down_revision = '5b81f7e9caee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
