"""init schema

Revision ID: 55fb6778919b
Revises: 5086920271d7
Create Date: 2025-06-08 02:37:12.498875-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55fb6778919b'
down_revision = '5086920271d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
