"""init schema

Revision ID: 5b71c901b75f
Revises: 2660694a469a
Create Date: 2025-07-13 07:38:28.920682-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b71c901b75f'
down_revision = '2660694a469a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
