"""init schema

Revision ID: 5b81f7e9caee
Revises: ec4e84b8e8de
Create Date: 2025-08-16 02:26:48.978828-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b81f7e9caee'
down_revision = 'ec4e84b8e8de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
