"""init schema

Revision ID: 600646ff51de
Revises: 962d701bba75
Create Date: 2025-06-21 14:39:01.234054-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '600646ff51de'
down_revision = '962d701bba75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
