"""init schema

Revision ID: 631631bd5f6c
Revises: 4cd6b84e5660
Create Date: 2025-08-15 11:43:43.538147-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '631631bd5f6c'
down_revision = '4cd6b84e5660'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
