"""init schema

Revision ID: 651cea824b9f
Revises: d438068a79e3
Create Date: 2025-08-16 01:41:38.726578-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '651cea824b9f'
down_revision = 'd438068a79e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
