"""init schema

Revision ID: 65243f2729c3
Revises: fb46636ed3f5
Create Date: 2025-08-15 13:49:02.540062-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65243f2729c3'
down_revision = 'fb46636ed3f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
