"""init schema

Revision ID: 65d933b633e8
Revises: 29a9636b112d
Create Date: 2025-06-08 01:49:53.100167-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65d933b633e8'
down_revision = '29a9636b112d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
