"""init schema

Revision ID: 6b0fac79bd74
Revises: 48d91eb43dd8
Create Date: 2025-06-22 08:07:49.960928-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b0fac79bd74'
down_revision = '48d91eb43dd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
