"""init schema

Revision ID: 72b988da0e12
Revises: ef930cc6b38c
Create Date: 2025-08-15 12:39:04.767038-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72b988da0e12'
down_revision = 'ef930cc6b38c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
