"""init schema

Revision ID: 73105bd4e175
Revises: 22532f892a08
Create Date: 2025-06-11 13:28:56.662890-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73105bd4e175'
down_revision = '22532f892a08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
