"""init schema

Revision ID: 7880a921b94c
Revises: 55fb6778919b
Create Date: 2025-06-08 02:38:30.144381-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7880a921b94c'
down_revision = '55fb6778919b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
