"""init schema

Revision ID: 7eef5ee314fd
Revises: 24b4e1a7d8ee
Create Date: 2025-06-11 13:51:49.285921-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eef5ee314fd'
down_revision = '24b4e1a7d8ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
