"""init schema

Revision ID: 8395ffd2f91b
Revises: 18cdd6cbce6d
Create Date: 2025-08-16 01:18:35.190784-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8395ffd2f91b'
down_revision = '18cdd6cbce6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
