"""init schema

Revision ID: 8509bbca2300
Revises: 1bb8fd7f486c
Create Date: 2025-08-15 14:57:38.874172-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8509bbca2300'
down_revision = '1bb8fd7f486c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
