"""init schema

Revision ID: 8e9eefbe166e
Revises: 1ff989b9872a
Create Date: 2025-06-08 02:34:01.909169-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e9eefbe166e'
down_revision = '1ff989b9872a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
