"""init schema

Revision ID: 8f561b1a8f95
Revises: 9e38d7e9d450
Create Date: 2025-06-08 01:33:52.081121-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f561b1a8f95'
down_revision = '9e38d7e9d450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
