"""init schema

Revision ID: 9276bda8de99
Revises: 1441d16034f1
Create Date: 2025-08-15 09:46:29.098970-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9276bda8de99'
down_revision = '1441d16034f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
