"""init schema

Revision ID: 941695c3e378
Revises: f62323437a2f
Create Date: 2025-06-08 01:35:59.014082-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '941695c3e378'
down_revision = 'f62323437a2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
