"""init schema

Revision ID: 94b010cbe06d
Revises: 651cea824b9f
Create Date: 2025-08-16 02:18:18.389908-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94b010cbe06d'
down_revision = '651cea824b9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
