"""init schema

Revision ID: 9a1a1b8d5827
Revises: ee15ff7d7806
Create Date: 2025-08-15 09:53:11.499105-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a1a1b8d5827'
down_revision = 'ee15ff7d7806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
