"""init schema

Revision ID: 9e38d7e9d450
Revises: d50f642788c5
Create Date: 2025-06-08 01:24:25.762769-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e38d7e9d450'
down_revision = 'd50f642788c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_tile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('is_constructible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('x', 'y', name='uq_tile_coordinates')
    )
    op.add_column('village', sa.Column('map_tile_id', sa.Integer(), nullable=False))
    op.drop_constraint('uq_village_coordinates', 'village', type_='unique')
    op.create_unique_constraint(None, 'village', ['map_tile_id'])
    op.create_foreign_key(None, 'village', 'map_tile', ['map_tile_id'], ['id'])
    op.drop_column('village', 'y')
    op.drop_column('village', 'x')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('village', sa.Column('x', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('village', sa.Column('y', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'village', type_='foreignkey')
    op.drop_constraint(None, 'village', type_='unique')
    op.create_unique_constraint('uq_village_coordinates', 'village', ['x', 'y'])
    op.drop_column('village', 'map_tile_id')
    op.drop_table('map_tile')
    # ### end Alembic commands ###
