"""init schema

Revision ID: ae2d59ac64cf
Revises: 65243f2729c3
Create Date: 2025-08-15 13:50:50.717557-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae2d59ac64cf'
down_revision = '65243f2729c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
