"""init schema

Revision ID: b146acec0879
Revises: 32aa091cc808
Create Date: 2025-08-16 10:21:10.836612-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b146acec0879'
down_revision = '32aa091cc808'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
