"""init schema

Revision ID: b34db533e724
Revises: ca3845a0d6b8
Create Date: 2025-06-20 13:35:46.747712-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b34db533e724'
down_revision = 'ca3845a0d6b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
