"""init schema

Revision ID: b654b5a1638f
Revises: bd4f415f0234
Create Date: 2025-06-11 14:07:40.123235-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b654b5a1638f'
down_revision = 'bd4f415f0234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
