"""init schema

Revision ID: bb8471fc989d
Revises: ae2d59ac64cf
Create Date: 2025-08-15 13:52:18.941888-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb8471fc989d'
down_revision = 'ae2d59ac64cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
