"""init schema

Revision ID: bdfcccd355c0
Revises: 7880a921b94c
Create Date: 2025-06-08 02:39:45.765447-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdfcccd355c0'
down_revision = '7880a921b94c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
