"""init schema

Revision ID: caf957266c3c
Revises: 65b5820caa67
Create Date: 2025-08-16 15:14:15.023289-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caf957266c3c'
down_revision = '65b5820caa67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
