"""init schema

Revision ID: ce2ad17bb914
Revises: 04cee76d7b4d
Create Date: 2025-08-15 13:22:23.817993-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce2ad17bb914'
down_revision = '04cee76d7b4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
