"""init schema

Revision ID: d2dc9c378cbf
Revises: 2b49c84525d9
Create Date: 2025-08-15 11:58:49.462597-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2dc9c378cbf'
down_revision = '2b49c84525d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
