"""init schema

Revision ID: d38e8f757e43
Revises: d51e7ffff2d3
Create Date: 2025-06-22 07:37:07.237558-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd38e8f757e43'
down_revision = 'd51e7ffff2d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
