"""init schema

Revision ID: d51e7ffff2d3
Revises: 5cee10a368f8
Create Date: 2025-06-22 07:14:15.854258-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd51e7ffff2d3'
down_revision = '5cee10a368f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
