"""init schema

Revision ID: d6bc3afd752d
Revises: b838fd71980e
Create Date: 2025-06-08 01:44:21.808200-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6bc3afd752d'
down_revision = 'b838fd71980e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
