"""init schema

Revision ID: d9d5d0649e50
Revises: 941695c3e378
Create Date: 2025-06-08 01:38:03.514942-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9d5d0649e50'
down_revision = '941695c3e378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tribe_attributes', sa.Column('bonus', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tribe_attributes', 'bonus')
    # ### end Alembic commands ###
