"""init schema

Revision ID: daf8bce0467b
Revises: 8509bbca2300
Create Date: 2025-08-15 14:59:29.696273-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daf8bce0467b'
down_revision = '8509bbca2300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
