"""init schema

Revision ID: ee15ff7d7806
Revises: 4a2ca894ddef
Create Date: 2025-08-15 09:48:29.029601-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee15ff7d7806'
down_revision = '4a2ca894ddef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
