"""init schema

Revision ID: ee87e178cea5
Revises: 30d1b94d44e1
Create Date: 2025-08-16 01:23:37.044737-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee87e178cea5'
down_revision = '30d1b94d44e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
