"""init schema

Revision ID: ef930cc6b38c
Revises: d2dc9c378cbf
Create Date: 2025-08-15 12:01:01.495159-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef930cc6b38c'
down_revision = 'd2dc9c378cbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
