"""init schema

Revision ID: f42905a9be87
Revises: 8df35eef0d35
Create Date: 2025-07-14 05:03:26.466622-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f42905a9be87'
down_revision = '8df35eef0d35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
