"""init schema

Revision ID: f84719263ab5
Revises: b146acec0879
Create Date: 2025-08-16 10:36:16.463769-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f84719263ab5'
down_revision = 'b146acec0879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
