"""init schema

Revision ID: fe3a4ceae315
Revises: c670e6d1968d
Create Date: 2025-06-22 07:51:25.065896-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe3a4ceae315'
down_revision = 'c670e6d1968d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
