name: Front End Deployment on GCS

on:
  push:
    branches: [ "main" ]

jobs:
  # To build the project
  build-front:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./travian/frontend/
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checking out code
        uses: actions/checkout@v3

      - id: 'Authenticate to Google Cloud'
      name: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/157663317275/locations/global/workloadIdentityPools/github/providers/github-provider'
        service_account: 'github-actions@second-strand-395917.iam.gserviceaccount.com'

      - name: Installing dependencies
        run: npm install

      - name: Building project
        run: npm run build

      - name: Deploy project
        run: gsutil cp -r dist/* gs://travian.lol