name: Deploy FastAPI to Cloud Run

on:
  push:
    branches: [main]

env:
  PROJECT_ID: vallorium
  REGION: europe-west9
  REPOSITORY_ID: api
  IMAGE_NAME: fastapi

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.DEPLOY_SA_EMAIL }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker europe-west9-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t europe-west9-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_ID/$IMAGE_NAME:${{ github.sha }} .
          docker push europe-west9-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_ID/$IMAGE_NAME:${{ github.sha }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend-config=envs/prod.backend.hcl

      - name: Terraform Apply
        run: terraform apply -auto-approve \
          -var-file=envs/prod.tfvars \
          -var="image_tag=${{ github.sha }}"
