name: Back End Deployment on Cloud Run

on:
  push:
    branches: [ "main" ]

jobs:
  # To build the project
  build-back:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./travian/backend/
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checking out code
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v1.1.1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Fix Auth
        run: yes | gcloud auth login --cred-file="$GOOGLE_APPLICATION_CREDENTIALS"

      - name: Deploy to Cloud Build  
        run:  gcloud builds submit --tag gcr.io/travian-dev-395914/test:1.0.0 .
        options:
          logging: CLOUD_LOGGING_ONLY

      - name: Deploy to Cloud Run 
        run:  gcloud run services update app --image=gcr.io/travian-dev-395914/test:1.0.0 --port=8000 --region=us-central1 --platform managed