name: Front End Deployment on GCS

on:
  push:
    branches: [ "main" ]

jobs:
  # To build the project
  build-tambola:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./travian/frontend/
    steps:
      - name: Checking out code
        uses: actions/checkout@v3
        
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Installing dependencies
        run: npm install

      - name: Building project
        run: npm run build