name: Front End Deployment on GCS

on:
  push:
    branches: [ "main" ]

jobs:
  # To build the project
  build-tambola:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./travian/frontend/
    steps:
      - name: Checking out code
        uses: actions/checkout@v3
      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Installing dependencies
        run: npm install
      - name: Building project
        run: npm run build