name: Front End Deployment on GCS

on:
  push:
    branches: [ "main" ]

jobs:
  # To build the project
  build-front:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./travian/frontend/
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checking out code
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v1.1.1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Fix Auth
        run: yes | gcloud auth login --cred-file="$GOOGLE_APPLICATION_CREDENTIALS"


      - name: Installing dependencies
        run: npm install

      - name: Building project
        run: npm run build

      - name: Deploy project
        run: gsutil cp -r dist/* gs://travian.lol