name: Deploy Terraform

on: [push]
jobs:
  build:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: Setup GCP Service Account
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true


      - name: Terraform init
        id: init
        run: |
          terraform --version
          terraform init
          terraform validate
        working-directory: travian/infrastructure

      - name: Terraform plan
        id: plan
        run: |
          terraform plan
        working-directory: travian/infrastructure