name: Deploy Terraform

on: [push]
jobs:
  Terraform:

    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1.2.1
        name: Setup Terraform
        with:
          terraform_version: 1.0.8
          terraform_wrapper: false
          # more setup-terraform configuration. See https://github.com/hashicorp/setup-terraform#usage

      - name: Terraform init
        id: init
        run: |
          terraform --version
          terraform init
          terraform validate